title: GMAG
logo: /assets/img/logo.png
description: Ground-based magnetometer package
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

arrays: /gmag/arrays
stations: /gmag/stations
